# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'GeekCourse' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GeekCourse
pod 'AFNetworking', '~> 3.1.0'
pod 'HYBMasonryAutoCellHeight', '~> 2.0.1'
pod 'SDWebImage', '~> 3.8.2'
 pod 'MJExtension', '~> 3.0.13'
pod 'MJRefresh', '~> 3.1.12'
pod 'JSONModel', '~> 1.5.1'
pod 'SDCycleScrollView', '~> 1.65'
pod 'CYLTableViewPlaceHolder', '~> 1.0.8'
pod 'MBProgressHUD', '~> 1.0.0'
end

